INSERT	INTO	`impresoras`	(nombre,	modelo,	serie,	ip,	mac,	edificio,	ubicacion)	VALUES(	'LIMPIEZA INTERIOR',	'ILBP352DN',	'NLQA002301',	'10.222.14.35',	'd849.2ff9.aa33',	'SERVICIOS AL INTERIOR',	'LIMPIEZA')	;
INSERT	INTO	`impresoras`	(nombre,	modelo,	serie,	ip,	mac,	edificio,	ubicacion)	VALUES(	'LAVANDERIA EXTERIOR',	'ILBP352DN',	'NLQA002299',	'10.222.17.173',	'd849.2ff9.aa40',	'CUARTELES',	'LAVANDERIA')	;
INSERT	INTO	`impresoras`	(nombre,	modelo,	serie,	ip,	mac,	edificio,	ubicacion)	VALUES(	'CAPTURA',	'ILBP352DN',	'NLQA002303',	'10.222.14.193',	'd849.2ff9.aa35',	'CENTRO MEDICO',	'LABORATORIO')	;
INSERT	INTO	`impresoras`	(nombre,	modelo,	serie,	ip,	mac,	edificio,	ubicacion)	VALUES(	'COMEDOR CUARTELES',	'ILBP352DN',	'NLQA002300',	'USB',	'N/A',	'CUARTELES',	'COMEDOR')	;
INSERT	INTO	`impresoras`	(nombre,	modelo,	serie,	ip,	mac,	edificio,	ubicacion)	VALUES(	'ALMACEN DE HERRAMIENTAS',	'ILBP352DN',	'NLQA002850',	'USB',	'N/A',	'SERVICIOS AL INTERIOR',	'ALMACEN DE HERRAMIENTAS')	;
INSERT	INTO	`impresoras`	(nombre,	modelo,	serie,	ip,	mac,	edificio,	ubicacion)	VALUES(	'HEMATOLOGIA',	'ILBP352DN',	'NLQA002793',	'USB',	'N/A',	'CENTRO MEDICO',	'LABORATORIO')	;
INSERT	INTO	`impresoras`	(nombre,	modelo,	serie,	ip,	mac,	edificio,	ubicacion)	VALUES(	'QUIMICA CLINICA',	'ILBP352DN',	'NLQA002790',	'USB',	'N/A',	'CENTRO MEDICO',	'LABORATORIO')	;
INSERT	INTO	`impresoras`	(nombre,	modelo,	serie,	ip,	mac,	edificio,	ubicacion)	VALUES(	'FARMACIA',	'ILBP352DN',	'NLQA002794',	'USB',	'N/A',	'CENTRO MEDICO',	'FARMACIA')	;
INSERT	INTO	`impresoras`	(nombre,	modelo,	serie,	ip,	mac,	edificio,	ubicacion)	VALUES(	'STOCK',	'ILBP352DN',	'NLQA002825',	'STOCK',	'N/A',	'SERVICIOS AL INTERIOR',	'IDF')	;
INSERT	INTO	`impresoras`	(nombre,	modelo,	serie,	ip,	mac,	edificio,	ubicacion)	VALUES(	'DIRECCION CCO',	'ILBP352DN',	'NLQA002748',	'USB',	'N/A',	'CCO',	'DIRECCION CCO')	;
INSERT	INTO	`impresoras`	(nombre,	modelo,	serie,	ip,	mac,	edificio,	ubicacion)	VALUES(	'SERVICIOS MEDICOS',	'ILBP352DN',	'NLQA002826',	'STOCK',	'N/A',	'CCO',	'STOCK')	;
INSERT	INTO	`impresoras`	(nombre,	modelo,	serie,	ip,	mac,	edificio,	ubicacion)	VALUES(	'TITULAR',	'MF525DW',	'2BH06343',	'STOCK',	'N/A',	'EDIFICIO DE GOBIERNO',	'STOCK')	;
INSERT	INTO	`impresoras`	(nombre,	modelo,	serie,	ip,	mac,	edificio,	ubicacion)	VALUES(	'GUARDA',	'MF525DW',	'2BH06411',	'10.222.18.21',	'00bb.c17a.7c12',	'ANEXO GARITA',	'OFICIALIA DE GUARDA')	;
INSERT	INTO	`impresoras`	(nombre,	modelo,	serie,	ip,	mac,	edificio,	ubicacion)	VALUES(	'JEFATURA ALMACEN',	'MF525DW',	'2BH06405',	'USB',	'N/A',	'ALMACEN GENERAL',	'JEFATURA')	;
INSERT	INTO	`impresoras`	(nombre,	modelo,	serie,	ip,	mac,	edificio,	ubicacion)	VALUES(	'MONITOREO INTELIGENCIA',	'MF525DW',	'2BH03821',	'USB',	'N/A',	'EDIFICIO DE GOBIERNO',	'MONITOREO INTELIGENCIA')	;
INSERT	INTO	`impresoras`	(nombre,	modelo,	serie,	ip,	mac,	edificio,	ubicacion)	VALUES(	'INDUSTRIA NAVE 5',	'MF525DW',	'2BH03827',	'10.222.17.235',	'00bb.c17a.57ae',	'INDUSTRIA',	'NAVE 5 RECEPCION')	;
INSERT	INTO	`impresoras`	(nombre,	modelo,	serie,	ip,	mac,	edificio,	ubicacion)	VALUES(	'STOCK',	'MF525DW',	'2BH03553',	'STOCK',	'N/A',	'CCO',	'STOCK')	;
INSERT	INTO	`impresoras`	(nombre,	modelo,	serie,	ip,	mac,	edificio,	ubicacion)	VALUES(	'STOCK',	'MF525DW',	'2BH03818',	'STOCK',	'N/A',	'CCO',	'STOCK')	;
INSERT	INTO	`impresoras`	(nombre,	modelo,	serie,	ip,	mac,	edificio,	ubicacion)	VALUES(	'ALMACEN 1',	'MF525DW',	'2BH03555',	'USB',	'N/A',	'ALMACEN GENERAL',	'ALMACEN 1')	;
INSERT	INTO	`impresoras`	(nombre,	modelo,	serie,	ip,	mac,	edificio,	ubicacion)	VALUES(	'ALMACEN 2',	'MF525DW',	'2BH03828',	'USB',	'N/A',	'ALMACEN GENERAL',	'ALMACEN 2')	;
INSERT	INTO	`impresoras`	(nombre,	modelo,	serie,	ip,	mac,	edificio,	ubicacion)	VALUES(	'VIDEOCONFERENCIAS',	'MF525DW',	'2BH03830',	'10.222.17.242',	'f80d.609d.f7fb',	'DORMITORIO F',	'VIDEOCONFERENCIAS')	;
INSERT	INTO	`impresoras`	(nombre,	modelo,	serie,	ip,	mac,	edificio,	ubicacion)	VALUES(	'LAVANDERIA INTERIOR',	'MF525DW',	'2BH03832',	'10.222.18.33',	'00bb.c17a.58bb',	'SERVICIOS AL INTERIOR',	'LAVANDERIA')	;
INSERT	INTO	`impresoras`	(nombre,	modelo,	serie,	ip,	mac,	edificio,	ubicacion)	VALUES(	'AUDIENCIAS',	'MF525DW',	'2BH03822',	'10.222.18.15',	'00bb.c17a.58ba',	'AREA EDUCATIVA',	'FORMACION PROFESIONAL')	;
INSERT	INTO	`impresoras`	(nombre,	modelo,	serie,	ip,	mac,	edificio,	ubicacion)	VALUES(	'MTTO INTERIOR',	'MF525DW',	'2BH03817',	'10.222.18.36',	'00bb.c17a.5f46',	'SERVICIOS AL INTERIOR',	'MANTENIMIENTO')	;
INSERT	INTO	`impresoras`	(nombre,	modelo,	serie,	ip,	mac,	edificio,	ubicacion)	VALUES(	'STOCK',	'MF525DW',	'2BH03824',	'STOCK',	'N/A',	'CCO',	'STOCK')	;
INSERT	INTO	`impresoras`	(nombre,	modelo,	serie,	ip,	mac,	edificio,	ubicacion)	VALUES(	'OFICINA LABORATORIO',	'MF525DW',	'2BH03823',	'10.222.14.175',	'00bb.c17a.57a4',	'CENTRO MEDICO',	'LABORATORIO')	;
INSERT	INTO	`impresoras`	(nombre,	modelo,	serie,	ip,	mac,	edificio,	ubicacion)	VALUES(	'ALMACEN 3',	'MF525DW',	'2BH06341',	'USB',	'N/A',	'ALMACEN GENERAL',	'ALMACEN 3')	;
INSERT	INTO	`impresoras`	(nombre,	modelo,	serie,	ip,	mac,	edificio,	ubicacion)	VALUES(	'TIENDA C',	'MF525DW',	'2BH06406',	'10.222.17.233',	'00bb.c17a.7a80',	'INDUSTRIA',	'NAVE 5 TIENDAS')	;
INSERT	INTO	`impresoras`	(nombre,	modelo,	serie,	ip,	mac,	edificio,	ubicacion)	VALUES(	'TECNOLOGIAS CCO',	'MF525DW',	'2BH06400',	'10.222.39.175',	'00bb.c17a.7a86',	'CCO',	'OFICINAS DE TECNOLOGIAS')	;
INSERT	INTO	`impresoras`	(nombre,	modelo,	serie,	ip,	mac,	edificio,	ubicacion)	VALUES(	'BANCOS',	'IRA4545I',	'2QD06902',	'10.222.17.247',	'f80d.609d.f5e3',	'ANEXO GARITA',	'BANCOS')	;
INSERT	INTO	`impresoras`	(nombre,	modelo,	serie,	ip,	mac,	edificio,	ubicacion)	VALUES(	'BIBLIOTECA',	'IRA4545I',	'2QD07026',	'10.222.18.227',	'f80d.609b.58d2',	'AREA EDUCATIVA',	'BIBLIOTECA')	;
INSERT	INTO	`impresoras`	(nombre,	modelo,	serie,	ip,	mac,	edificio,	ubicacion)	VALUES(	'DORMITORIO D',	'IRA4545I',	'2QD06919',	'10.222.12.240',	'f80d.609b.5616',	'DORMITORIO D',	'EPM PLANTA ALTA')	;
INSERT	INTO	`impresoras`	(nombre,	modelo,	serie,	ip,	mac,	edificio,	ubicacion)	VALUES(	'OFICINAS CCO',	'IRA4545I',	'2QD06918',	'10.222.39.240',	'f80d.609d.f7f4',	'CCO',	'OFICINAS ADMINISTRATIVAS')	;
INSERT	INTO	`impresoras`	(nombre,	modelo,	serie,	ip,	mac,	edificio,	ubicacion)	VALUES(	'MESA DE AYUDA',	'IRA4545I',	'2QD07023',	'10.222.39.245',	'f80d.609b.58d3',	'CCO',	'MESA DE AYUDA')	;
INSERT	INTO	`impresoras`	(nombre,	modelo,	serie,	ip,	mac,	edificio,	ubicacion)	VALUES(	'DORMITORIO E',	'IRA4545I',	'2QD06913',	'10.222.17.242',	'f80d.609d.f7fb',	'CENTRO MEDICO',	'COMANDANCIA')	;
INSERT	INTO	`impresoras`	(nombre,	modelo,	serie,	ip,	mac,	edificio,	ubicacion)	VALUES(	'CENTRO MEDICO (SALA?)',	'IRA4545I',	'2QD07008',	'10.222.18.241',	'f80d.609b.5822',	'CENTRO MEDICO',	'(SALA?)')	;
INSERT	INTO	`impresoras`	(nombre,	modelo,	serie,	ip,	mac,	edificio,	ubicacion)	VALUES(	'AREA EDUCATIVA',	'IRA4545I',	'2QD06873',	'10.222.18.228',	'f80d.609b.5445',	'AREA EDUCATIVA',	'EPM PLANTA ALTA')	;
INSERT	INTO	`impresoras`	(nombre,	modelo,	serie,	ip,	mac,	edificio,	ubicacion)	VALUES(	'EPM A',	'IRA4545I',	'2QD07024',	'10.222.17.179',	'f80d.609d.fa33',	'EDIFICIO DE GOBIERNO',	'RESGUARDO')	;
INSERT	INTO	`impresoras`	(nombre,	modelo,	serie,	ip,	mac,	edificio,	ubicacion)	VALUES(	'EMP C',	'IRA4545I',	'2QD06916',	'10.222.13.241',	'f80d.609d.f7fa',	'DORMITORIO C',	'EPM PLANTA ALTA')	;
INSERT	INTO	`impresoras`	(nombre,	modelo,	serie,	ip,	mac,	edificio,	ubicacion)	VALUES(	'ADMIN RECEPCION',	'IRA4545I',	'2QD07029',	'10.222.17.244',	'f80d.609d.fb06',	'EDIFICIO DE GOBIERNO',	'CHECADORES')	;
INSERT	INTO	`impresoras`	(nombre,	modelo,	serie,	ip,	mac,	edificio,	ubicacion)	VALUES(	'ADMINISTRACION',	'IRA4545I',	'2QD06914',	'10.222.17.249',	'f80d.609b.5614',	'EDIFICIO DE GOBIERNO',	'ADMINISTRACION')	;
INSERT	INTO	`impresoras`	(nombre,	modelo,	serie,	ip,	mac,	edificio,	ubicacion)	VALUES(	'TRABAJO SOCIAL',	'IRA4545I',	'2QD07006',	'10.222.18.72',	'USB',	'ANEXO GARITA',	'TRABAJO SOCIAL')	;
INSERT	INTO	`impresoras`	(nombre,	modelo,	serie,	ip,	mac,	edificio,	ubicacion)	VALUES(	'CENTRO MEDICO (JEFATURA?)',	'IRA4545I',	'2QD07018',	'10.222.17.229',	'f80d.609d.f9be',	'CENTRO MEDICO',	'(JEFATURA?)')	;
INSERT	INTO	`impresoras`	(nombre,	modelo,	serie,	ip,	mac,	edificio,	ubicacion)	VALUES(	'ARCHIVO JURIDICO',	'IRA4545I',	'2QD07021',	'10.222.17.246',	'f80d.609b.57c2',	'EDIFICIO DE GOBIERNO',	'ARCHIVO JURIDICO')	;
INSERT	INTO	`impresoras`	(nombre,	modelo,	serie,	ip,	mac,	edificio,	ubicacion)	VALUES(	'INDUSTRIA',	'IRA4545I',	'2QD06871',	'10.222.12.102',	'f80d.609d.f5c5',	'INDUSTRIA',	'EPM PLANTA ALTA')	;
INSERT	INTO	`impresoras`	(nombre,	modelo,	serie,	ip,	mac,	edificio,	ubicacion)	VALUES(	'EPM B',	'IRA4545I',	'2QD07226',	'10.222.14.240',	'f80d.609b.5b31',	'DORMITORIO B',	'EPM PLANTA ALTA')	;
INSERT	INTO	`impresoras`	(nombre,	modelo,	serie,	ip,	mac,	edificio,	ubicacion)	VALUES(	'JURIDICO BLANCO Y NEGRO',	'IRA4545I',	'2QD07230',	'10.222.17.243',	'f80d.609b.5b32',	'EDIFICIO DE GOBIERNO',	'JURIDICO')	;
INSERT	INTO	`impresoras`	(nombre,	modelo,	serie,	ip,	mac,	edificio,	ubicacion)	VALUES(	'EPM F',	'IRA4545I',	'2QD06915',	'10.222.17.163',	'f80d.609b.5613',	'DORMITORIO F',	'EPM PLANTA ALTA')	;
INSERT	INTO	`impresoras`	(nombre,	modelo,	serie,	ip,	mac,	edificio,	ubicacion)	VALUES(	'SEGURIDAD',	'IRA4545I',	'2QD06901',	'10.222.17.239',	'f80d.609b.543e',	'EDIFICIO DE GOBIERNO',	'DIRECCION JURIDICO')	;
INSERT	INTO	`impresoras`	(nombre,	modelo,	serie,	ip,	mac,	edificio,	ubicacion)	VALUES(	'COMUNICACIÓN CCO',	'C356IF',	'2QC06968',	'10.222.39.14',	'00c0.ee86.b2ce',	'CCO',	'COMUNICACIÓN')	;
INSERT	INTO	`impresoras`	(nombre,	modelo,	serie,	ip,	mac,	edificio,	ubicacion)	VALUES(	'JURIDICO COLOR',	'C356IF',	'2QC06969',	'10.222.17.245',	'7438.b7a7.6f6c',	'EDIFICIO DE GOBIERNO',	'JURIDICO')	;
INSERT	INTO	`impresoras`	(nombre,	modelo,	serie,	ip,	mac,	edificio,	ubicacion)	VALUES(	'INFORMATICA',	'C356IF',	'2QC07011',	'10.222.17.240',	'7438.b7a7.6fd4',	'EDIFICIO DE GOBIERNO',	'INFORMATICA')	;
INSERT	INTO	`impresoras`	(nombre,	modelo,	serie,	ip,	mac,	edificio,	ubicacion)	VALUES(	'MONITOREO COLOR',	'C356IF',	'2QC06700',	'USB CONTROL',	'N/A',	'EDIFICIO DE GOBIERNO',	'MONITOREO')	;
INSERT	INTO	`impresoras`	(nombre,	modelo,	serie,	ip,	mac,	edificio,	ubicacion)	VALUES(	'PPA',	'C356IF',	'2QC06802',	'10.222.18.226',	'7438.b7a7.0b32',	'SERVICIOS AL INTERIOR',	'PPA')	;
INSERT	INTO	`impresoras`	(nombre,	modelo,	serie,	ip,	mac,	edificio,	ubicacion)	VALUES(	'ASISTENTE DIRECCION CCO',	'C356IF',	'2QC06905',	'USB ASIST CCO',	'N/A',	'CCO',	'ASISTENTE DIRECCION')	;
INSERT	INTO	`impresoras`	(nombre,	modelo,	serie,	ip,	mac,	edificio,	ubicacion)	VALUES(	'DIRECCION GENERAL',	'C356IF',	'2QC07007',	'10.222.17.241',	'7438.b7a7.6fd0',	'EDIFICIO DE GOBIERNO',	'DIRECCION GENERAL')	;
INSERT	INTO	`impresoras`	(nombre,	modelo,	serie,	ip,	mac,	edificio,	ubicacion)	VALUES(	'STOCK',	'IRA4225',	'QHJ07179',	'STOCK',	'N/A',	'CCO',	'STOCK')	;
INSERT	INTO	`impresoras`	(nombre,	modelo,	serie,	ip,	mac,	edificio,	ubicacion)	VALUES(	'STOCK',	'IRAC3330I',	'QTV06629',	'STOCK',	'N/A',	'CCO',	'STOCK')	;
INSERT	INTO	`impresoras`	(nombre,	modelo,	serie,	ip,	mac,	edificio,	ubicacion)	VALUES(	'STOCK',	'DRG2140',	'JF301459',	'STOCK',	'N/A',	'CCO',	'STOCK')	;
INSERT	INTO	`impresoras`	(nombre,	modelo,	serie,	ip,	mac,	edificio,	ubicacion)	VALUES(	'STOCK',	'TX-4000',	'AFMM00877',	'STOCK',	'N/A',	'CCO',	'STOCK')	;
INSERT	INTO	`impresoras`	(nombre,	modelo,	serie,	ip,	mac,	edificio,	ubicacion)	VALUES(	'PLOTTER JEFE INFORMATICA',	'TX-4000',	'AFMM00904',	'10.222.17.111',	'74bf.c0d9.d0db',	'EDIFICIO DE GOBIERNO',	'INFORMATICA')	;
INSERT	INTO	`impresoras`	(nombre,	modelo,	serie,	ip,	mac,	edificio,	ubicacion)	VALUES(	'PLOTTER INFORMATICA',	'TX-4000',	'AFMM00898',	'10.222.17.248',	'PENDIENTE',	'EDIFICIO DE GOBIERNO',	'INFORMATICA')	;
INSERT	INTO	`impresoras`	(nombre,	modelo,	serie,	ip,	mac,	edificio,	ubicacion)	VALUES(	'STOCK',	'TX-4000',	'AFMM00903',	'STOCK',	'N/A',	'CCO',	'STOCK')	;
INSERT	INTO	`impresoras`	(nombre,	modelo,	serie,	ip,	mac,	edificio,	ubicacion)	VALUES(	'STOCK',	'UNIFLOW',	'XY0039913',	'N/A',	'N/A',	'CCO',	'STOCK')	;

INSERT	INTO	`usuarios`	(username,	password,	nombre,	puesto,	enabled)	VALUES(	'IValenzuela',	'$2a$10$TouI5VTUf4eNbdO1tJkNW.j0.DKVT9bxWpvv.Ntg3r0kGiVmtwRnS',	'Ildefonso Valenzuela Lopez',	'Especialista',	1)	;
INSERT	INTO	`usuarios`	(username,	password,	nombre,	puesto,	enabled)	VALUES(	'JDiaz',	'$2a$10$FJl9Z0ZlO6nCJWR9cFxlXeemkAFr.aG/AAFbhg1Ys5CsS8AnMZv8m',	'Jesus Diaz Rivera',	'Especialista',	1)	;
INSERT	INTO	`usuarios`	(username,	password,	nombre,	puesto,	enabled)	VALUES(	'JGaytan',	'$2a$10$k4cm.Y63UqCtv0JhXJUTm.iBHdlRO7Q5aTavsyicxDvdoB/2wMRxK',	'Juan Carlos Gaytan Flores',	'Especialista',	1)	;
INSERT	INTO	`usuarios`	(username,	password,	nombre,	puesto,	enabled)	VALUES(	'JRamirez',	'$2a$10$N7iMpNO4e5cQ9/fsM46p3ueAMDHLHhAv5vZsunb4AnQAA2gMDIx/e',	'Josafat Ramirez Cortez',	'Supervisor',	1)	;
INSERT	INTO	`usuarios`	(username,	password,	nombre,	puesto,	enabled)	VALUES(	'KGallegos',	'$2a$10$hAjjuQ97m54UzbzBotWPpehhxHhshNoJ9YB6FZmVJloprzE2EjVq.',	'Karina Gallegos Emiliano',	'Tecnico',	1)	;
INSERT	INTO	`usuarios`	(username,	password,	nombre,	puesto,	enabled)	VALUES(	'ALuna',	'$2a$10$oywhQae5yIIctHecbNQCwu/hSY8plmM/Lpugezw9rnJZUPE33UNrm',	'Angel Lopez Luna',	'Auxiliar',	1)	;
INSERT	INTO	`usuarios`	(username,	password,	nombre,	puesto,	enabled)	VALUES(	'HLopez',	'$2a$10$CGaTIpdiQBAqxXj3wd0iG.YNd.raFHaJEOaDNf6aNmE2ANxgR.RPK',	'Hector Lopez Torre',	'Auxiliar',	1)	;
INSERT	INTO	`usuarios`	(username,	password,	nombre,	puesto,	enabled)	VALUES(	'UReyes',	'$2a$10$IsdL096duG8G6xH33iS2uuppuCMQ6YImCuO7ZnenuC5NJ.SemFMpm',	'Uriel Reyes Hernandez',	'Auxiliar',	1)	;
INSERT	INTO	`usuarios`	(username,	password,	nombre,	puesto,	enabled)	VALUES(	'RUbillo',	'$2a$10$Du.S8JhEl/QzbGSp0jAe.OrpVC.kR9..//2CqCbP8w7O3Xl9RuqTG',	'Roberto Ubillo Sanchez',	'Tecnico',	1)	;
INSERT	INTO	`usuarios`	(username,	password,	nombre,	puesto,	enabled)	VALUES(	'RGonzalez',	'$2a$10$QUWmd1dGN9P.yTgukzT0r.zq6CdU4H0OTklIsKaWd0KbM9KDfHCY2',	'Rodolfo Gonzalez Juarez',	'Auxiliar',	1)	;


INSERT INTO `roles` (name) VALUES('ROLE_ADMIN');

INSERT INTO `usuarios_roles` (usuario_id, roles_id) VALUES(1, 1);
INSERT INTO `usuarios_roles` (usuario_id, roles_id) VALUES(2, 1);

INSERT INTO `controltoner` (contador102, contador109, contador124, fecha, toner, impresora_id, usuario_id) VALUES(100, 50, 50, '2021-04-14', 'negro', 1, 1);

